apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  Job1:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        id: sha
        run: |
          echo "hello world"
          git log -n 1 --format="%H"
          echo "$(git log -n 1 --format="%H")" > "$CLOUDBEES_OUTPUTS/id"

      - name: Publish workflow evidence item
        uses: cloudbees-io/publish-evidence-item@v1
        if: '${{always()}}'
        with:
          content: |
            ${{steps.sha.outputs.id}}