apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "0.0.229"
          digest: "sha256:adf1ea1c8737d2237e98897ded3b6064194f5bc9162f9e14e2517a62306f56b3"
          url: "docker.io/cbpautomation/python-hello-world-docker:0.0.229"
          target-environment: "PROD"

